version: '2'
services:
  
  python-seed:
    image: python:latest
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./datasets:/datasets
    command: >
      /bin/bash -c "
      cd datasets/ &&
      pip install lxml &&
      pip install pymongo &&
      python3 convXMLtoJSON.py MapaRuas-materialBase/texto/ MapaRuas-materialBase/atual/"

  mongodb:
    container_name: mongodbContainer
    image: mongo:latest
    ports:
      - "27017:27017"