services:

  frontend:
    container_name: proj_ruas_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - backend
    links:
      - backend

  backend:
    container_name: proj_ruas_servico_dados
    build:
      context: ./servico_dados
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    container_name: proj_ruas_mongodb
    image: mongo:latest