services:

  backend:
    container_name: proj_ruas_servico_dados
    build:
      context: ./servico_dados
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    container_name: proj_ruas_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
