services:

  parser:
    container_name: proj_ruas_parser
    build:
      context: ./datasets
      dockerfile: Dockerfile
    volumes:
      - ./datasets:/datasets
    depends_on:
      - mongodb

  mongodb:
    container_name: proj_ruas_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"